### ISSUE TITLE
Enable Mac ARM build

### ISSUE THREAD

**Issue by kylebarron** [conda-forge/arro3-core-feedstock#7]
osx arm is not currently building it appears: https://prefix.dev/channels/conda-forge/packages/arro3-core ref https://github.com/xarray-contrib/xdggs/pull/67/commits/6ca24de5fb6cc3baf55ce46b42ee97d33aacf580#r1797734406

**Comment by keewis** [comment]
I tried looking into this, but I can't seem to be able to figure out what that would be (plus I don't have any experience with packaging rust packages). Maybe try pinging the appropriate help team?

**Comment by kylebarron** [comment]
I figure first we should find a more popular rust-based python library, check if it builds for Mac arm, and then see how its recipe is defined

**Comment by keewis** [comment]
it looks like you'll have to manually [request](https://conda-forge.org/docs/maintainer/knowledge_base/#apple-silicon-builds) osx-arm64 builds

**Comment by kylebarron** [comment]
I made https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6546

**Comment by kylebarron** [comment]
Should be fixed by https://github.com/conda-forge/arro3-core-feedstock/pull/13

**Comment by kylebarron** [comment]
Looks like it worked! https://prefix.dev/channels/conda-forge/packages/arro3-core

![Image](https://github.com/user-attachments/assets/3d3a840e-17d5-4c24-8d5d-46a7f0143523)
